### ISSUE TITLE
tests are depending on python2.7

### ISSUE THREAD

**Issue by thekorn** [tobami/littlechef#119]
Other than stated in the README the testsuite is not working with python 2.6, because `unittest.TestCase.assertIn` is new in python 2.7:

``` python
======================================================================
ERROR: test_list_recipes (test_lib.TestLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markus/devel/littlechef/tests/test_lib.py", line 254, in test_list_recipes
    self.assertIn('subversion::testrecipe', [r['name'] for r in recipes])
AttributeError: 'TestLib' object has no attribute 'assertIn'
```

So please either change the requirement, or update this test.
@tobami I'd prefer staying with py2.6 and changing the test, WDYT?
